### ISSUE TITLE
Selenium reports "Selenium binary is not a firefox executable" on Ubuntu 22

### ISSUE THREAD

**Issue by GrahamBenHarper** [corbin-ch/bcdl#1]
OS: Ubuntu 22
bcdl SHA: 975e1749405712e358be5b4b1ef91acf82f560f4
Selenium version: 4.27.1
Python version: 3.10.12

When running on Ubuntu, there's a problem with the Selenium interface that reports
```
Traceback (most recent call last):
  File "/home/grahambenharper/bcdl/./bcdl.py", line 598, in <module>
    main()
  File "/home/grahambenharper/bcdl/./bcdl.py", line 62, in main
    shared_driver = init_driver(GLOBALS)
  File "/home/grahambenharper/bcdl/./bcdl.py", line 159, in init_driver
    shared_driver = webdriver.Firefox()
  File "/home/grahambenharper/.local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/grahambenharper/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/grahambenharper/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/grahambenharper/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/grahambenharper/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable
```

This is not caused by the bcdl, but it's an odd quirk with Selenium's compatibility with Ubuntu's choice of installing Firefox as a snap. For more details, see, for example, [this post on StackExchange](https://stackoverflow.com/questions/76846675/selenium-ubuntu22-bug-message-binary-is-not-a-firefox-executable).

Following that StackExchange post, a proposed fix is to pass the path as an optional flag with default `None` and modify `init_driver` to cover both cases
```python
def init_driver(GLOBALS):
    if GLOBALS['geckodriver_executable'] == None:
        shared_driver = webdriver.Firefox()
    else:
        geckodriver_path = GLOBALS['geckodriver_executable']
        driver_service = webdriver.FirefoxService(executable_path=geckodriver_path)
        shared_driver = webdriver.Firefox(service=driver_service)
    return shared_driver
```

I've confirmed this works on Ubuntu 22 using `--geckodriver-executable="/snap/bin/geckodriver"` as an additional argument. I'm happy to open a PR for this if you'd like since I've already made the changes locally.

**Comment by corbin-zip** [comment]
Thank you for bringing this up! I'm glad to accept PRs if you have the time, otherwise I will make the changes proposed in your GitHub issues when I find the time myself!

Corbin

Sent from Proton Mail Android

-------- Original Message --------
