### ISSUE TITLE
Single-track downloads do not need to be unzipped, resulting in a runtime error

### ISSUE THREAD

**Issue by GrahamBenHarper** [corbin-ch/bcdl#2]
OS: Ubuntu 22
bcdl SHA: 975e1749405712e358be5b4b1ef91acf82f560f4

When attempting to download a single track, the regex for `zip_name` fails to find the zip file because the downloaded file is an unzipped file in the requested format. bcdl throws the following error:
```
Downloading #1 of 1...
Traceback (most recent call last):
  File "/home/grahambenharper/bcdl/./bcdl.py", line 584, in <module>
    main()
  File "/home/grahambenharper/bcdl/./bcdl.py", line 63, in main
    download_albums(selected_list, shared_driver, GLOBALS)
  File "/home/grahambenharper/bcdl/./bcdl.py", line 538, in download_albums
    zip_name = re.findall(zip_name_regex, zip_name_pre_regex)[0]
IndexError: list index out of range
```

This can be a little problematic when downloading 100 albums and the single-track download immediately causes the program to crash after 5 minutes of collecting download links. The easiest way to avoid this problem is to check if the regex result is `[]` with something like 
```
            zip_name_res_regex = re.findall(zip_name_regex, zip_name_pre_regex)
            if (len(zip_name_res_regex) == 0):
                # error checking, new regex, a continue statement, or download without unzipping here?
            zip_name = zip_name_res_regex[0]
```
In my case, inside the if statement I printed `download_url` to the terminal followed by a `continue` statement, and I downloaded it manually afterward, which is not a problem when there are only a few single tracks to download, but it would be better if the `zip_name_regex` also covered the non-zip file scenario for the single-track downloads.

Here's an example of the variables I see on my end when attempting to download one of these single tracks if this is helpful to you:
```
    zip_name_regex = r'(?<=filename\*=UTF-8\'\').+?(?=.zip)'
    zip_name_pre_regex = "attachment; filename=\"white shinobi - garden in a bottle.mp3\"; filename*=UTF-8''white%20shinobi%20-%20garden%20in%20a%20bottle.mp3"
```

Also, thank you for the awesome app. I really appreciate your hard work. It's a wonderful, simple app that does exactly what I want.

**Comment by corbin-zip** [comment]
After listening to a handful of vaporwave tapes and solving endless captchas, I think I have a fix here: https://github.com/corbin-zip/bcdl/commit/3ec20dfdd71de280d4243d23612cad4f8e0847ee

but I've discovered #4 in the process. Perhaps I'll work on that later :) for the time being, I've supplied a manual workaround in the description of the issue.

Thank you for creating this issue and my apologies for taking so long to resolve it. Your details were extremely helpful in developing a fix however and I very much appreciate it!

Corbin
